In [94]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt

In [95]:
df=pd.read_csv("course_lead_scoring_2026.csv")
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

Data preparation

In [96]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [97]:
df.dtypes

lead_source                  object
industry                     object
employment_status            object
location                     object
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [98]:
catg=list(df.dtypes[df.dtypes=='object'].index)
numl=list(df.dtypes[(df.dtypes=='float64') |(df.dtypes=='int64') ].index)

In [99]:
for c  in catg:
    df[c]=df[c].fillna('NA')
    
for v in numl:
    df[v]=df[v].fillna(0.0)

In [100]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [101]:
numl=['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train),len(df_val),len(df_test)

(3000, 1000, 1000)

In [104]:
df_train=df_train.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)

y_train=df_train.converted.values
y_test=df_test.converted.values
y_val=df_val.converted.values

del df_train['converted']
del df_test['converted']
del df_val['converted']

Question 1: ROC AUC feature importance

In [105]:
from sklearn.metrics import roc_auc_score

In [106]:
for v in numl:
     auc_v=roc_auc_score(y_train, df_train[v])
     if auc_v < 0.5:
        auc_v=roc_auc_score(y_train, -df_train[v]) 
     print(v,round(auc_v,3))

annual_income 0.608
number_of_courses_viewed 0.723
interaction_count 0.765
lead_score 0.788

Question 2: Training the model

In [107]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

In [108]:
train_dicts=df_train.to_dict(orient='records')
val_dicts=df_val.to_dict(orient='records')

dv=DictVectorizer(sparse=False)
x_train=dv.fit_transform(train_dicts)
x_val=dv.transform(val_dicts)

model=LogisticRegression(solver='liblinear',C=1.0, max_iter=1000)
model.fit(x_train,y_train)

y_pred=model.predict_proba(x_val)[:,1]
auc=roc_auc_score(y_val,y_pred)
print(round(auc,3))

0.732

Question 3: Precision and Recall

In [109]:
scores=[]
thresholds=np.linspace(0, 1, 101)
for t in thresholds:
    actual_positive=(y_val==1)
    actual_negative=(y_val==0)
    predict_positive=(y_pred>=t)
    predict_negative=(y_pred<t)

    tp=(predict_positive & actual_positive).sum()
    tn=(predict_negative & actual_negative).sum()

    fp=(predict_positive & actual_negative).sum()
    fn=(predict_negative & actual_positive).sum()
    
    scores.append((t, tp, fp, fn, tn))
    
columns = ['threshold', 'tp', 'fp', 'fn', 'tn']
df_scores = pd.DataFrame(scores, columns=columns)

df_scores['Presion'] = df_scores.tp / (df_scores.tp + df_scores.fp)
df_scores['recall'] = df_scores.tp / (df_scores.tp + df_scores.fn)

In [110]:
pd.set_option('display.max_rows', None)
df_scores

     threshold   tp   fp   fn   tn   Presion    recall
0         0.00  586  414    0    0  0.586000  1.000000
1         0.01  586  414    0    0  0.586000  1.000000
2         0.02  586  414    0    0  0.586000  1.000000
3         0.03  586  414    0    0  0.586000  1.000000
4         0.04  586  414    0    0  0.586000  1.000000
5         0.05  586  414    0    0  0.586000  1.000000
6         0.06  586  414    0    0  0.586000  1.000000
7         0.07  586  414    0    0  0.586000  1.000000
8         0.08  586  414    0    0  0.586000  1.000000
9         0.09  586  414    0    0  0.586000  1.000000
10        0.10  586  414    0    0  0.586000  1.000000
11        0.11  586  414    0    0  0.586000  1.000000
12        0.12  586  414    0    0  0.586000  1.000000
13        0.13  586  414    0    0  0.586000  1.000000
14        0.14  586  414    0    0  0.586000  1.000000
15        0.15  586  414    0    0  0.586000  1.000000
16        0.16  586  414    0    0  0.586000  1.000000
17        0.17  586  414    0    0  0.586000  1.000000
18        0.18  586  414    0    0  0.586000  1.000000
19        0.19  586  414    0    0  0.586000  1.000000
20        0.20  586  414    0    0  0.586000  1.000000
21        0.21  586  414    0    0  0.586000  1.000000
22        0.22  586  414    0    0  0.586000  1.000000
23        0.23  586  414    0    0  0.586000  1.000000
24        0.24  586  414    0    0  0.586000  1.000000
25        0.25  586  414    0    0  0.586000  1.000000
26        0.26  586  413    0    1  0.586587  1.000000
27        0.27  586  411    0    3  0.587763  1.000000
28        0.28  586  405    0    9  0.591322  1.000000
29        0.29  586  405    0    9  0.591322  1.000000
30        0.30  586  403    0   11  0.592518  1.000000
31        0.31  585  396    1   18  0.596330  0.998294
32        0.32  583  395    3   19  0.596115  0.994881
33        0.33  583  393    3   21  0.597336  0.994881
34        0.34  583  386    3   28  0.601651  0.994881
35        0.35  583  384    3   30  0.602896  0.994881
36        0.36  583  381    3   33  0.604772  0.994881
37        0.37  579  375    7   39  0.606918  0.988055
38        0.38  577  373    9   41  0.607368  0.984642
39        0.39  576  369   10   45  0.609524  0.982935
40        0.40  573  362   13   52  0.612834  0.977816
41        0.41  572  352   14   62  0.619048  0.976109
42        0.42  568  348   18   66  0.620087  0.969283
43        0.43  564  342   22   72  0.622517  0.962457
44        0.44  560  338   26   76  0.623608  0.955631
45        0.45  554  328   32   86  0.628118  0.945392
46        0.46  548  319   38   95  0.632065  0.935154
47        0.47  543  313   43  101  0.634346  0.926621
48        0.48  540  306   46  108  0.638298  0.921502
49        0.49  535  301   51  113  0.639952  0.912969
50        0.50  531  294   55  120  0.643636  0.906143
51        0.51  520  284   66  130  0.646766  0.887372
52        0.52  515  278   71  136  0.649433  0.878840
53        0.53  508  264   78  150  0.658031  0.866894
54        0.54  501  256   85  158  0.661823  0.854949
55        0.55  492  245   94  169  0.667571  0.839590
56        0.56  486  234  100  180  0.675000  0.829352
57        0.57  478  226  108  188  0.678977  0.815700
58        0.58  471  212  115  202  0.689605  0.803754
59        0.59  464  203  122  211  0.695652  0.791809
60        0.60  457  190  129  224  0.706337  0.779863
61        0.61  453  177  133  237  0.719048  0.773038
62        0.62  437  165  149  249  0.725914  0.745734
63        0.63  425  155  161  259  0.732759  0.725256
64        0.64  408  151  178  263  0.729875  0.696246
65        0.65  392  137  194  277  0.741021  0.668942
66        0.66  377  127  209  287  0.748016  0.643345
67        0.67  363  116  223  298  0.757829  0.619454
68        0.68  348  105  238  309  0.768212  0.593857
69        0.69  325   94  261  320  0.775656  0.554608
70        0.70  311   82  275  332  0.791349  0.530717
71        0.71  291   70  295  344  0.806094  0.496587
72        0.72  278   62  308  352  0.817647  0.474403
73        0.73  261   56  325  358  0.823344  0.445392
74        0.74  241   48  345  366  0.833910  0.411263
75        0.75  218   42  368  372  0.838462  0.372014
76        0.76  204   37  382  377  0.846473  0.348123
77        0.77  188   32  398  382  0.854545  0.320819
78        0.78  176   28  410  386  0.862745  0.300341
79        0.79  159   27  427  387  0.854839  0.271331
80        0.80  139   23  447  391  0.858025  0.237201
81        0.81  124   20  462  394  0.861111  0.211604
82        0.82  110   16  476  398  0.873016  0.187713
83        0.83   95   13  491  401  0.879630  0.162116
84        0.84   79    9  507  405  0.897727  0.134812
85        0.85   62    8  524  406  0.885714  0.105802
86        0.86   47    6  539  408  0.886792  0.080205
87        0.87   39    4  547  410  0.906977  0.066553
88        0.88   32    3  554  411  0.914286  0.054608
89        0.89   27    2  559  412  0.931034  0.046075
90        0.90   19    1  567  413  0.950000  0.032423
91        0.91   11    1  575  413  0.916667  0.018771
92        0.92    8    1  578  413  0.888889  0.013652
93        0.93    6    0  580  414  1.000000  0.010239
94        0.94    3    0  583  414  1.000000  0.005119
95        0.95    2    0  584  414  1.000000  0.003413
96        0.96    1    0  585  414  1.000000  0.001706
97        0.97    0    0  586  414       NaN  0.000000
98        0.98    0    0  586  414       NaN  0.000000
99        0.99    0    0  586  414       NaN  0.000000
100       1.00    0    0  586  414       NaN  0.000000

Question 4: F1 score

In [111]:
df_scores['f1_score'] = 2*((df_scores['Presion']*df_scores['recall']) / (df_scores['Presion']+df_scores['recall']))

In [112]:
df_scores.sort_values(by='f1_score',ascending=False)

     threshold   tp   fp   fn   tn   Presion    recall  f1_score
41        0.41  572  352   14   62  0.619048  0.976109  0.757616
42        0.42  568  348   18   66  0.620087  0.969283  0.756325
43        0.43  564  342   22   72  0.622517  0.962457  0.756032
45        0.45  554  328   32   86  0.628118  0.945392  0.754768
44        0.44  560  338   26   76  0.623608  0.955631  0.754717
46        0.46  548  319   38   95  0.632065  0.935154  0.754301
48        0.48  540  306   46  108  0.638298  0.921502  0.754190
40        0.40  573  362   13   52  0.612834  0.977816  0.753452
47        0.47  543  313   43  101  0.634346  0.926621  0.753121
50        0.50  531  294   55  120  0.643636  0.906143  0.752658
49        0.49  535  301   51  113  0.639952  0.912969  0.752461
39        0.39  576  369   10   45  0.609524  0.982935  0.752449
36        0.36  583  381    3   33  0.604772  0.994881  0.752258
37        0.37  579  375    7   39  0.606918  0.988055  0.751948
38        0.38  577  373    9   41  0.607368  0.984642  0.751302
35        0.35  583  384    3   30  0.602896  0.994881  0.750805
34        0.34  583  386    3   28  0.601651  0.994881  0.749839
51        0.51  520  284   66  130  0.646766  0.887372  0.748201
53        0.53  508  264   78  150  0.658031  0.866894  0.748159
52        0.52  515  278   71  136  0.649433  0.878840  0.746918
31        0.31  585  396    1   18  0.596330  0.998294  0.746650
33        0.33  583  393    3   21  0.597336  0.994881  0.746479
54        0.54  501  256   85  158  0.661823  0.854949  0.746091
32        0.32  583  395    3   19  0.596115  0.994881  0.745524
61        0.61  453  177  133  237  0.719048  0.773038  0.745066
56        0.56  486  234  100  180  0.675000  0.829352  0.744257
30        0.30  586  403    0   11  0.592518  1.000000  0.744127
55        0.55  492  245   94  169  0.667571  0.839590  0.743764
28        0.28  586  405    0    9  0.591322  1.000000  0.743183
29        0.29  586  405    0    9  0.591322  1.000000  0.743183
58        0.58  471  212  115  202  0.689605  0.803754  0.742317
60        0.60  457  190  129  224  0.706337  0.779863  0.741281
57        0.57  478  226  108  188  0.678977  0.815700  0.741085
59        0.59  464  203  122  211  0.695652  0.791809  0.740623
27        0.27  586  411    0    3  0.587763  1.000000  0.740366
26        0.26  586  413    0    1  0.586587  1.000000  0.739432
1         0.01  586  414    0    0  0.586000  1.000000  0.738966
0         0.00  586  414    0    0  0.586000  1.000000  0.738966
25        0.25  586  414    0    0  0.586000  1.000000  0.738966
12        0.12  586  414    0    0  0.586000  1.000000  0.738966
2         0.02  586  414    0    0  0.586000  1.000000  0.738966
3         0.03  586  414    0    0  0.586000  1.000000  0.738966
4         0.04  586  414    0    0  0.586000  1.000000  0.738966
5         0.05  586  414    0    0  0.586000  1.000000  0.738966
6         0.06  586  414    0    0  0.586000  1.000000  0.738966
7         0.07  586  414    0    0  0.586000  1.000000  0.738966
8         0.08  586  414    0    0  0.586000  1.000000  0.738966
9         0.09  586  414    0    0  0.586000  1.000000  0.738966
10        0.10  586  414    0    0  0.586000  1.000000  0.738966
24        0.24  586  414    0    0  0.586000  1.000000  0.738966
11        0.11  586  414    0    0  0.586000  1.000000  0.738966
13        0.13  586  414    0    0  0.586000  1.000000  0.738966
14        0.14  586  414    0    0  0.586000  1.000000  0.738966
15        0.15  586  414    0    0  0.586000  1.000000  0.738966
16        0.16  586  414    0    0  0.586000  1.000000  0.738966
17        0.17  586  414    0    0  0.586000  1.000000  0.738966
18        0.18  586  414    0    0  0.586000  1.000000  0.738966
19        0.19  586  414    0    0  0.586000  1.000000  0.738966
20        0.20  586  414    0    0  0.586000  1.000000  0.738966
21        0.21  586  414    0    0  0.586000  1.000000  0.738966
22        0.22  586  414    0    0  0.586000  1.000000  0.738966
23        0.23  586  414    0    0  0.586000  1.000000  0.738966
62        0.62  437  165  149  249  0.725914  0.745734  0.735690
63        0.63  425  155  161  259  0.732759  0.725256  0.728988
64        0.64  408  151  178  263  0.729875  0.696246  0.712664
65        0.65  392  137  194  277  0.741021  0.668942  0.703139
66        0.66  377  127  209  287  0.748016  0.643345  0.691743
67        0.67  363  116  223  298  0.757829  0.619454  0.681690
68        0.68  348  105  238  309  0.768212  0.593857  0.669875
69        0.69  325   94  261  320  0.775656  0.554608  0.646766
70        0.70  311   82  275  332  0.791349  0.530717  0.635342
71        0.71  291   70  295  344  0.806094  0.496587  0.614572
72        0.72  278   62  308  352  0.817647  0.474403  0.600432
73        0.73  261   56  325  358  0.823344  0.445392  0.578073
74        0.74  241   48  345  366  0.833910  0.411263  0.550857
75        0.75  218   42  368  372  0.838462  0.372014  0.515366
76        0.76  204   37  382  377  0.846473  0.348123  0.493349
77        0.77  188   32  398  382  0.854545  0.320819  0.466501
78        0.78  176   28  410  386  0.862745  0.300341  0.445570
79        0.79  159   27  427  387  0.854839  0.271331  0.411917
80        0.80  139   23  447  391  0.858025  0.237201  0.371658
81        0.81  124   20  462  394  0.861111  0.211604  0.339726
82        0.82  110   16  476  398  0.873016  0.187713  0.308989
83        0.83   95   13  491  401  0.879630  0.162116  0.273775
84        0.84   79    9  507  405  0.897727  0.134812  0.234421
85        0.85   62    8  524  406  0.885714  0.105802  0.189024
86        0.86   47    6  539  408  0.886792  0.080205  0.147105
87        0.87   39    4  547  410  0.906977  0.066553  0.124006
88        0.88   32    3  554  411  0.914286  0.054608  0.103060
89        0.89   27    2  559  412  0.931034  0.046075  0.087805
90        0.90   19    1  567  413  0.950000  0.032423  0.062706
91        0.91   11    1  575  413  0.916667  0.018771  0.036789
92        0.92    8    1  578  413  0.888889  0.013652  0.026891
93        0.93    6    0  580  414  1.000000  0.010239  0.020270
94        0.94    3    0  583  414  1.000000  0.005119  0.010187
95        0.95    2    0  584  414  1.000000  0.003413  0.006803
96        0.96    1    0  585  414  1.000000  0.001706  0.003407
97        0.97    0    0  586  414       NaN  0.000000       NaN
98        0.98    0    0  586  414       NaN  0.000000       NaN
99        0.99    0    0  586  414       NaN  0.000000       NaN
100       1.00    0    0  586  414       NaN  0.000000       NaN

Question 5: 5-Fold CV

In [113]:
from sklearn.model_selection import KFold

In [ ]:
def train(df_train, y_train, C):
    dicts = df_train[catg+numl].to_dict(orient='records')

    dv = DictVectorizer(sparse=False)
    X_train=dv.fit_transform(dicts)

    model = LogisticRegression(solver='liblinear',C=C, max_iter=1000)
    model.fit(X_train, y_train)
    
    return dv, model

In [115]:
def predict(df, dv, model):
    dicts = df[catg+numl].to_dict(orient='records')

    X = dv.transform(dicts)
    y_pred = model.predict_proba(X)[:, 1]

    return y_pred

In [118]:
scores_auc_roc=[]
kfold=KFold(n_splits=5, shuffle=True, random_state=1)
for train_idx, val_idx in kfold.split(df_full_train):
    df_train=df_full_train.iloc[train_idx]
    df_val=df_full_train.iloc[val_idx]
    
    df_train=df_train.reset_index(drop=True)
    df_val=df_val.reset_index(drop=True)

    y_train = df_train.converted.values
    y_val = df_val.converted.values

    del df_train['converted']
    del df_val['converted']
    
    dv,model=train(df_train, y_train,1.0)
    y_pred=predict(df_val,dv,model)

    scores_auc_roc.append(roc_auc_score(y_val, y_pred))

print(scores_auc_roc)
print(np.std(scores_auc_roc).round(3))

[0.7305601027122453, 0.7295726148196622, 0.7363428071259397, 0.7412454717957564, 0.7209138590326581]
0.007


Question 6: Hyperparameter Tuning

In [120]:
for C in [0.000001, 0.001, 1]:
    scores_auc_roc = []
    kfold=KFold(n_splits=5, shuffle=True, random_state=1)
    for train_idx, val_idx in kfold.split(df_full_train):
        df_train=df_full_train.iloc[train_idx]
        df_val=df_full_train.iloc[val_idx]
        
        df_train=df_train.reset_index(drop=True)
        df_val=df_val.reset_index(drop=True)

        y_train=df_train.converted.values
        y_val=df_val.converted.values

        del df_train['converted']
        del df_val['converted']
        
        dv,model=train(df_train, y_train,C)
        y_pred=predict(df_val,dv,model)

        scores_auc_roc.append(roc_auc_score(y_val, y_pred))

    print(C,round(np.mean(scores_auc_roc),3),round(np.std(scores_auc_roc),3))

1e-06 0.617 0.019
0.001 0.749 0.01
1 0.732 0.007